### ISSUE TITLE
Reduce the set of default special characters to only the most commonly accepted.

### ISSUE THREAD

**Issue by jpgoldberg** [1Password/spg#14]
Currently, our default is symbol set is `"!#%)*+,-.:=>?@]^_}~"`. We should reduce that dramatically to those things that are going to be most widely accepted.

Note that in the past, @robyoder made recommendations along these lines, as has @mitchchn. @dteare has expressed interest.

In broader terms, I did try to encourage a broader open project to build upon work that has been going on.

**Comment by robyoder** [comment]
I've contacted Moritz Horsch to ask if his PRD database is publicly available. It would be nice to actually run some stats instead of guessing which symbols are the best.

**Comment by mitchchn** [comment]
Some sets fo consider:

** Most Frequently-Used Special Characters in 10 Million Passwords**
https://www.reddit.com/r/dataisbeautiful/comments/2vfgvh/most_frequentlyused_special_characters_in_10/

**The 1337-speak set**

`!@$&`

**The #$@&-ing swear word set**

`#$@&%*!`

**Comment by jpgoldberg** [comment]
I never thought I would ever say this, but let's go l33t.

**Comment by jpgoldberg** [comment]
The leet set contains things that I believe are more likely to be problems on sites (`&` and `$`). So might want to use . and - instead.

**Comment by robyoder** [comment]
I agree on `&$`. I think we should start with `_-.!@` from the most frequently used list.
