### ISSUE TITLE
Handle impossible ranges for randomUint32()

### ISSUE THREAD

**Issue by jpgoldberg** [1Password/spg#7]
Related issue #5

After merging #6 we have the following

```go
func randomUint32n(n uint32) uint32 {
	if n <= 1 {
		return 0
	}
```
which seems wrong to me (and @Sc00bz). 0 is a possible return value when `randomUint32n()` is called with sane values (such as 1). But when n < 1, we are doing the equivalent of division by zero.

Because this isn't an exported function, we have some freedom here.

1. We can keep the convenient current behavior, even if it is semantically peculiar as long as we are careful not to rely on it.
2. We can panic. This is annoying for something that is called as a library, but there are times when you do want libraries to panic
3. We can report an error. That is make this return both an int and an error state. This is annoying because it would complicate all of the places it is called.

I can be persuaded to go with any of those. 

/cc @Sc00bz @robyoder @mitchchn

**Comment by robyoder** [comment]
I don't want to do 3, although it's likely the most proper solution. There's no reason to add in error handling for a function like this.

The only impossible case is 0, but my reasoning was that both 0 and 1 should be invalid values for this function because 1 will always produce 0 and thus displays no randomness, so You're Holding It Wrong™.

If you feel strongly about it, we can switch back to 2.

**Comment by Sc00bz** [comment]
In every place `randomUint32n` is called n is checked to not be zero. Except here: https://github.com/1Password/spg/blob/06557be73ffb44e672df08519b0bd839943cd870/char_gen.go#L103

So I'd go with 2 and add a check for `len(chars)` being zero. The reason for panicking even though it can't happen currently is for future code that's broken. If it panics the library is broken.

I disagree with calling `randomUint32n` with 1 is an error. It will complicate things like a function that takes a deck of cards and you want to get n random cards. If you want to use that function to a shuffled the full deck, then the last card picked is a random card from a set of 1 card. Oh right or a function that generates passwords with no repeated characters like [this](https://github.com/Sc00bz/generate-password/blob/c17daaaf76cfed87f170e17a8c3f22bf679de143/src/genpw.cpp#L240-L246).

**Comment by jpgoldberg** [comment]
> my reasoning was that both 0 and 1 should be invalid values for this function because 1 will always produce 0 bits and thus displays no randomness, so You're Holding It Wrong™.

I think returning 0 is perfect fine when that is the correct answer, as it is for a length of 1. Although we didn't implement the SeparatorChar this way, we could have done so with it picking "randomly" from a string of length 1. While wasteful, that would be a perfectly coherent thing to do.

I also agree that we should code defensively, and that (oddly enough) means deliberately panicking or returning an error. Just as we (correctly) panic if the CSPRNG returns an error, we should panic or error on what is very much like a division by zero.

While I've got no strong feelings between 2 and 3, I don't like 1, so I will implement option 2.
